version: "3"
services:
    mysql:
        container_name: phonoBook.mysql
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: phonoBook
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 4306:3306
        # バインドマウント
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - default

    php:
        container_name: phonoBook.php
        build:
            context: ./docker/php
            dockerfile: Dockerfile.dev
        image: php:phonoBook
        volumes:
            - ./code:/var/www/html
        depends_on:
            - mysql
        networks:
            - default

    nginx:
        container_name: phonoBook.nginx
        image: nginx:1.15.6
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./code:/var/www/html
        depends_on:
            - php
        ports:
            - 8001:80
        networks:
            - default

# defaultのネットワークを使用
networks:
    default:
        external: false

#(プロジェクト毎にボリュームを作成する場合)
volumes:
    mysql-data:
        external: false

# デフォルトだと無名のVolume(データの永続化領域)が生成してしまうので明示
# servicesで指定するvolumes(バインドマウント)とは無関係
# external:で外部で作成しているプロジェクト用MySQLのボリュームを指定
# dooker downで削除しても消えない
# (既存のボリュームを指定する場合)
# volumes:
#     mysql-data:
#         external:
#             name: project-mysql
