version: "3"
services:
    mysql:
        container_name: phonoBook.mysql
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: phonoBook
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 4306:3306
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - phonoBook-net

    php:
        container_name: phonoBook.php
        build: ./docker/php
        image: php:phonoBook
        volumes:
            - ./code:/var/www/html
        depends_on:
            - mysql
        networks:
            - phonoBook-net

    nginx:
        container_name: phonoBook.nginx
        image: nginx:1.15.6
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./code:/var/www/html
        depends_on:
            - php
        ports:
            - 8001:80
        networks:
            - phonoBook-net

networks:
    phonoBook-net:
        driver: bridge

volumes:
  mysql-data:
