version: "3"
services:
    mysql:
        container_name: phonoBook.mysql
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: phonoBook
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 4306:3306
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - network

    php:
        container_name: phonoBook.php
        build: ./docker/php
        image: php:phonoBook
        volumes:
            - ./code:/var/www/html
        # working_dir: /var/www/html
        # command: >
        #     bash -c
        #     "composer install
        #     && php artisan migrate
        #     && npm install"
        depends_on:
            - mysql
        networks:
            - network

    nginx:
        container_name: phonoBook.nginx
        image: nginx:1.15.6
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./code:/var/www/html
        depends_on:
            - php
        ports:
            - 8000:80
        networks:
            - network

networks:
    network:
        driver: bridge

volumes:
  mysql-data:
